sudo: required
dist: xenial
language: node_js
node_js:
  - node
  - lts/*
install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable
services:
  - xvfb
before_script:
  - npm install
  - bower install
  - npm run update-webdriver
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
addons:
  sonarcloud:
    organization: "scorpibear-github"
    token:
      secure: "OWrFTtkqAgukMMOlY5dtbfxw25H9bnXnZB89KCc4x3MDt71ISu7PYCw4Wnca/LQtxMUuw4INtoSQXVe2Nqon/KmG1LXzTE3hnPnsklPisjEdrzthUqoPNK5F32Jq9qHYBABnwxUESkLBy83RV3RHCqHjCpBEAOlch8h7WV3FXGw="
script:
  - ./node_modules/.bin/karma start --single-run
  - codecov
  - (npm start > /dev/null &) && (npm run e2e)
  - sonar-scanner

